### ISSUE TITLE
rules about keywords for new packages

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#10]
Should we do like in ::gentoo where you are only allowed to add new packages with amd64 and x86 arches?
There are some packages here keyworded for multiple arches but I suspect noone tested them (they are mostly leftovers from copy-paste).

I would also like a cleanup of those arches, people can request later a readdition of some of them provided that it works.

**Comment by lanodan** [comment]
Well I'm not so sure of that, we probably can't have `::gentoo` arch testers in guru for example so the keywording restriction is weird.

I think you can commit with keywords that you tested on `::guru` but if you're not sure it works you can just wait for someone to keyword it.
Maybe we could have a file listing guru-contributors who can do tests for arches? For example I have amd64, arm, mips64 and hopefully sparc64, ppc and arm64. But maybe QEMU is good enough for some small packages that do not need fast emulation.

**Comment by juippis** [comment]
I find the way Gentoo handles keywording outdated overall. The pattern currently is "it's not working, until proven otherwise" while I'd like to turn it around, "it's working, until proven otherwise". So to say, enable all non-experimental KEYWORDS by default, and if it's broken on certain arches, THEN call arch teams for help. 

So my suggestion here would be to allow stable arches by default. Or at least amd64, arm, arm64 and x86 which seem to be in a good state currently. As long as the deps allow it.

**Comment by heroxbd** [comment]
> Should we do like in ::gentoo where you are only allowed to add new packages with amd64 and x86 arches?
> There are some packages here keyworded for multiple arches but I suspect noone tested them (they are mostly leftovers from copy-paste).
> 
> I would also like a cleanup of those arches, people can request later a readdition of some of them provided that it works.

If the package has a backward incompatible update, then treat it as a new package.  Otherwise, it should be fine to keep exotic `~ARCH` in version bumps.

For a new package, only add `~ARCH` that you have actually tested, which implies if you have not tested 32-bit build, `~x86` should not be there either.

**Comment by Alessandro-Barbieri** [comment]
https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html

```Untested ARCHs in KEYWORDS

Please do not add other ARCHs into KEYWORDS unless the ebuild has been tested on that ARCH.```
