### ISSUE TITLE
Implement CI/CD

### ISSUE THREAD

**Issue by xgqt** [gentoo/guru#16]
It would be great to use one (or more) of CI/CD providers avilable on Github.
I'm personally a fan of Gitlab's own CI/CD but there a bunch of implementations on Github too.

**Comment by Bobbbay** [comment]
Update:  Gitlab just bumped their minutes to 400/group/month, with the availability to purchase more (something like $10 for 1000).

**Comment by AndrewAmmerlaan** [comment]
I copied these two files over from the ::science overlay: https://github.com/gentoo/sci/tree/master/.github/workflows and edited them a bit to run on the dev branch instead of the master branch.

Which seems to be giving us working repoman and pkgcheck checks: https://github.com/gentoo/guru/actions :smile:

**Comment by xgqt** [comment]
Very nice. Thanks for cooperation.

**Comment by Alessandro-Barbieri** [comment]
Is the CI also running on pull requests?

**Comment by AndrewAmmerlaan** [comment]
> Is the CI also running on pull requests?

Yes

**Comment by AndrewAmmerlaan** [comment]
> > Is the CI also running on pull requests?
> 
> Yes

But only on PRs to the dev branch, your PR is to the master branch, we can't merge directly to the master branch anyway so I didn't bother implementing the checks on the master branch.
