### ISSUE TITLE
Proliferation of live ebuilds

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#32]
Disclaimer: my opinion is biased, I don't like live ebuilds

I have noticed an ever incresing addition of live ebuilds here.
Do you _really_ use them or have you added them "because why not"?
I think of them as a maintenance burden: when you bump or modify a package you also have to check the live package too (doubling the effort).
Also they are really prone to build breakage for obvious reasons.
I strongly encourage you to drop the live ebuilds if you don't need them and switch to snapshot like packages (`<version>_p<date>` or `0_pre<date>`) if you need them.

**Comment by AndrewAmmerlaan** [comment]
I agree, I also don't like live ebuilds. Unless you're going to keep the live ebuild in sync with upstream very proactively they will break sooner or later. A snapshot ebuild on the other hand will stay functional for a lot longer, and requires less maintenance.

**Comment by telans** [comment]
I think I'm in the minority with this one. I don't *prefer* live ebuilds but I think they're certainly good to have for certain packages where commits are usually compatability/security/performance related. For packages like this I'm thinking dxvk, wine, bees.

Overall I don't think the maintenance burden is very high. If changes need to be made to a live ebuild between version releases then the changes can just be copied to the next version release. This can simplify bumping a great deal if you already know the package works. Theoretically there is no seperation between ebuilds at version release should `[[ ${PV} == 9999 ]]` templates be used (excluding packages which create branches for versions).

They will break eventually, but if you're looking to run *bleeding* edge it's expected. I don't see this as an issue when it's entirely opt-in through accept_keywords. There's no harm in leaving the option available if it's not broken all the time, but I suppose this all hinges on whether you're willing to maintain it or not. If yes, add it. If not, don't.

**Comment by AndrewAmmerlaan** [comment]
> I think they're certainly good to have for certain packages where commits are usually compatability/security/performance related. For packages like this I'm thinking dxvk, wine, bees.

Of course, they have their uses. I wouldn't want to ban them or anything, and if someone is willing to go through the extra effort of maintaining a live ebuild, who am I to stop them. However, there are also some cases where a live ebuild causes way more issues than it is worth IMO. I've had bad experience with live ebuilds for python packages, because python packages tend to change their dependencies very often, and `PYTHON_COMPAT` tends to get out of date. I'd imagine similar problems would occur with Lua and Ruby packages.

**Comment by telans** [comment]
> I've had bad experience with live ebuilds for python packages, because python packages tend to change their dependencies very often

I can see this issue with go and rust packages too...

**Comment by vowstar** [comment]
I've add ``bsc`` as a fixed version ``https://github.com/gentoo/guru/commit/bd164835a8b6d89c989f9fe4dcf9e0c71121d3b6``
Before this issue I've request upstream to tag a fixed (unique) release. The story is : https://github.com/B-Lang-org/bsc/issues/288
I also don't want use the 'live ebuild', but I have to use it because I'm contribute code to upstream.
Ban the 'live ebuild' not always good for new package, especially not good for developers who must use the latest package for some reason.
I agree to add a fixed version of the package, I oppose ban nightly build.

**Comment by jian-lin** [comment]
I use some live ebuilds for bug fixes that have not been released yet, e.g. `flaggie` and `alacritty`.

**Comment by Alessandro-Barbieri** [comment]
see https://bugs.gentoo.org/713802
