### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by juippis** [gentoo/guru#4]
Just noticed one can monitor the packaging status of Guru from repology, 
https://repology.org/projects/?search=&maintainer=&category=&inrepo=gentoo_ovl_guru&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on

**Comment by vowstar** [comment]
Already understood,
I found out that the package I maintain is outdated so I updated it immediately.

**Comment by AndrewAmmerlaan** [comment]
Wow this is really useful, I just version bumped some packages. It seems to be reporting that there is a newer version of python-vlc, but i couldn't find it on pypi so I skipped that one. It also confuses AXL with axl, which are in fact different packages. But other then that, this is way better then relying on GitHub release notifications.

**Comment by band-a-prend** [comment]
As far as I understand this page shows outdated package in comparison with versions of other repositories, e.i. compares with the latest known version of all repos.

**Comment by lanodan** [comment]
>this is way better then relying on GitHub release notifications.

Yeah, github notifications are really bad for this, I've been using RSS/Atom instead of them for getting releases (originally because releases would get lost in the pile of issues as they didn't have "release-only" until some months/one year ago) and it works much better, specially as not everything is on github and I also get for which repo it's for with tags/categories.
