### ISSUE TITLE
remove duplicate package dev-python/sniffio and dev-python/validators

### ISSUE THREAD

**Issue by fpemud** [gentoo/guru#40]
```
*       Repository "gentoo" and "guru" has same package "dev-python/sniffio"
*       Repository "gentoo" and "guru" has same package "dev-python/validators"
```

According to GURU regulations (https://wiki.gentoo.org/wiki/Project:GURU), they should be removed:
7. The primary purpose of GURU is to maintain packages not present in the Gentoo repository. Forking (overriding) actively maintained Gentoo packages into GURU is prohibited. If the package is moved to Gentoo, it should be removed from GURU.

**Comment by telans** [comment]
Added in:
 - https://github.com/gentoo/gentoo/commit/1e3fe61be090fe5a8e69a4bd3544f012ec975a2f
 - https://github.com/gentoo/gentoo/commit/bdec44f734437740d339a0b8e00e2c6b283c342b

It also looks like `dev-python/faker::guru` has been added to tree as `dev-python/Faker::gentoo`:
 - https://github.com/gentoo/gentoo/commit/f0fd0abeff968347999d2505505300e24c8bf139

**Comment by telans** [comment]
Also what command gave you that output of duplicate packages?

**Comment by fpemud** [comment]
The output is from a custom tool for myself.

I have checked the result manually.
```
fpemud@localhost ~/workspace/fpemud-refsystem $ ls /var/lib/portage/repo-gentoo/dev-python/sniffio -l
total 12
-rw-r--r-- 1 1003 1003 908 Feb  1 04:39 Manifest
-rw-r--r-- 1 1003 1003 371 Feb  1 03:39 metadata.xml
-rw-r--r-- 1 1003 1003 704 Feb  1 04:39 sniffio-1.2.0.ebuild
fpemud@localhost ~/workspace/fpemud-refsystem $ ls /var/lib/portage/repo-guru/dev-python/sniffio -l
total 12
-rw-r--r-- 1 root root 305 Jan  8 01:37 Manifest
-rw-r--r-- 1 root root 888 Jan  8 01:37 metadata.xml
-rw-r--r-- 1 root root 683 Jan  8 01:37 sniffio-1.2.0.ebuild

fpemud@localhost ~/workspace/fpemud-refsystem $ ls /var/lib/portage/repo-gentoo/dev-python/validators -l
total 12
-rw-r--r-- 1 1003 1003 913 Jan 31 08:43 Manifest
-rw-r--r-- 1 1003 1003 485 Jan 13 16:09 metadata.xml
-rw-r--r-- 1 1003 1003 501 Jan 31 08:43 validators-0.18.2.ebuild
fpemud@localhost ~/workspace/fpemud-refsystem $ ls /var/lib/portage/repo-guru/dev-python/validators -l
total 12
-rw-r--r-- 1 root root  309 Jan  8 01:37 Manifest
-rw-r--r-- 1 root root 1098 Jan  8 01:37 metadata.xml
-rw-r--r-- 1 root root  764 Jan  8 01:37 validators-0.18.2.ebuild
```

**Comment by telans** [comment]
> The output is from a custom tool for myself.

Mind sharing? It would be good to add it to the CI checks here

**Comment by AndrewAmmerlaan** [comment]
>  It would be good to add it to the CI checks here

That would be awesome. Something like this has been on the wish-list for some time now, but I never got around to actually doing it. In theory it should be simple, download the latest ::gentoo, list all directories in all categories and check for duplicate directories in ::guru, excluding capitalization, numbers, dashes and underscores. Sometimes a package has a different name, but it is still the same package. For those cases it might be possible to look for matching `DESCRIPTION`, `HOMEPAGE`, and/or `SRC_URI`.

**Comment by fpemud** [comment]
What I have done for duplication checking only focuses on packages with same name, which is trivial.
It is equivalent to the following bash script:
```
localhost ~ # cat find-same-package.sh 
#!/bin/sh
out1=`find $1 -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | sort | grep -Ev "^(eclass|licenses|metadata|profiles|scripts)/"`
out2=`find $2 -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | sort | grep -Ev "^(eclass|licenses|metadata|profiles|scripts)/"`
comm -12 <(echo "$out1") <(echo "$out2")

localhost ~ # ./find-same-package.sh /var/lib/portage/repo-gentoo/ /var/lib/portage/repo-guru/
dev-python/sniffio
dev-python/validators
```

**Comment by AndrewAmmerlaan** [comment]
> What I have done for duplication checking only focuses on packages with same name, which is trivial.
> It is equivalent to the following bash script:
> 
> ```
> localhost ~ # cat find-same-package.sh 
> #!/bin/sh
> out1=`find $1 -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | sort | grep -Ev "^(eclass|licenses|metadata|profiles|scripts)/"`
> out2=`find $2 -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | sort | grep -Ev "^(eclass|licenses|metadata|profiles|scripts)/"`
> comm -12 <(echo "$out1") <(echo "$out2")
> 
> localhost ~ # ./find-same-package.sh /var/lib/portage/repo-gentoo/ /var/lib/portage/repo-guru/
> dev-python/sniffio
> dev-python/validators
> ```

Thanks, I've used this as a starting point for a script that should automate the duplicate-check when it's done. I'm a bit busy with IRL things at the moment, but I should be able to get this up and running before the end of the week.

**Comment by AndrewAmmerlaan** [comment]
> > The output is from a custom tool for myself.
> 
> Mind sharing? It would be good to add it to the CI checks here

@telans I added a script and corresponding .github/workflow file to the dev branch. It checks for packages which have similar or identical names. It prints a warning if the package name is just similar, or identical in a different category, and prints an error if the package name is identical **and** in the same category (i.e. the package is overriding a package in ::gentoo) in which case the script exits with code 1 which will make the checks fail.

I did not exclude the license and eclass directory on purpose because it might be useful to detect overrides of licenses and eclasses as well. The checking is done after stripping the package name of: capitalization, numbers, dashes, underscores and pluses. I already found three duplicates with this script and removed them.

E.g. https://github.com/gentoo/guru/runs/1919794174?check_suite_focus=true

Let me know what you think, there might still be room for improvement. Currently it is rather slow because of the double for loop, but I'm unsure if and how this can be optimized.

@epsilon-0 @TheChymera Do you think something like this could be useful to ::science as well? (without the part where the checks fatally exit of course)

**Comment by epsilon-0** [comment]
Yes, this sounds lovely to have :heart:

**Comment by telans** [comment]
@AndrewAmmerlaan that's really cool and nice to have. What do you think of the changes I've made to make it a little faster?
Esentially I've just made the script regex check the package name before comparing exact package/category names.

diff: https://dpaste.com/65URVT7MA
new version: https://dpaste.com/FSRMZU8S9

It's lost the ability to find multiple possible package duplicates though. Not sure if that's that big of an issue however.

```
telans@genbox /var/db/repos/guru $ time ./scripts/check-duplicates.sh 

Checking for duplicates....

WARNING: The following packages closely match packages in the main Gentoo repository
        app-backup/b2::guru possible duplicate of net-mail/b4::gentoo
        app-portage/version::guru possible duplicate of perl-core/version::gentoo
        dev-R/R6::guru possible duplicate of dev-lang/R::gentoo
        dev-R/digest::guru possible duplicate of perl-core/Digest::gentoo
        dev-R/pkgconfig::guru possible duplicate of virtual/pkgconfig::gentoo
        dev-python/colored::guru possible duplicate of dev-ruby/colored2::gentoo
        dev-python/graphene::guru possible duplicate of media-libs/graphene::gentoo
        dev-python/gssapi::guru possible duplicate of dev-perl/GSSAPI::gentoo
        dev-python/hidapi::guru possible duplicate of licenses/HIDAPI::gentoo
        dev-python/libusb1::guru possible duplicate of virtual/libusb::gentoo
        media-gfx/glimpse::guru possible duplicate of app-misc/glimpse::gentoo
        sci-libs/kissfft::guru possible duplicate of dev-ruby/kissfft::gentoo
        sys-apps/dust::guru possible duplicate of dev-ruby/dust::gentoo
        sys-apps/hex::guru possible duplicate of dev-haskell/hex::gentoo
Please check these manually

ERROR: The following packages override packages in the main Gentoo repository
        sys-fs/compsize::guru exact match of sys-fs/compsize::gentoo
Please remove these packages

real    0m3.399s
user    0m3.372s
sys     0m0.029s
```
`sys-fs/compsize` is just a test dir I added.

**Comment by telans** [comment]
updated: https://dpaste.com/754BWAXYM

It now matches exactly what the current version does (multiple potential gentoo packages for a single guru package)

**Comment by AndrewAmmerlaan** [comment]
@telans Awesome, this is so much faster :open_mouth: 

I did not know about bash's `=~` operator, so I learned something today :smile: 

I changed one more thing in https://github.com/gentoo/guru/commit/04573fbb57a934aae0e23369b013c31f1a3e4969 for portability reasons. Now it reads the name of the repository from `profiles/repo_name` and uses that instead of hard-coding it to guru, I also renamed some variables accordingly. This way the script can be copy-pasted into other repositories without having to change the code.


> I did remove the number & symbol stripping from the package names but that can just be re-added if wanted

I re-added the striping of dashes and underscores from the package names, because a packaged could be named `foo-bar` in ::gentoo and `foo_bar` in ::guru, in which case it should still trigger a match. I'm undecided on the numbers, in my initial draft I was thinking of packages named `foo` and `foo2` which might or might not be duplicates. The plus symbol is a special case, because it is normally not allowed in package names but Gentoo has made an exception. E.g. a package could be named `foo-gtk` or `foo-gtk+` which may or may not be the same thing.
